---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 4
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: cont-1
          image: avinash8179/my-tetris:v1
          ports:
          - containerPort: 3000
